version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    user: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_PASSWORD=root # here this password can be set using the environment variable
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@user.com
      - PGADMIN_DEFAULT_PASSWORD=test
    ports:
      - "5050:80"
    restart: always

volumes: 
  pg_data:
