version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    user: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=<passsword> # ${POSTGRES_PASSWORD} # here this password can be set using the environment variable
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
