global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# alerts
rule_files:
  - "alert.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
  - job_name: "node"

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets:
          - localhost:9090
          - node-exporter:9100

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx, http_post_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - <targets>
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "192.168.29.179:9115" # Blackbox exporter.
      - target_label: region
        replacement: "local"
